apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: clnbgvi13-python 
  janus-idp.io/tekton: clnbgvi13-python
  backstage.io/kubernetes-id: clnbgvi13-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: clnbgvi13-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml