apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: clnbgvi13-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clnbgvi13-python 
  name: clnbgvi13-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: clnbgvi13-python 
